services:
  - type: web
    name: safarideserttours
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn desert_safari.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com,safarideserttours.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: safarideserttours-db
          property: connectionString
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

databases:
  - name: safarideserttours-db
    databaseName: safarideserttours
    user: safari
    plan: free 