# Generated by Django 5.2.1 on 2025-05-22 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('is_per_person', models.BooleanField(default=True, help_text='If checked, price is per person. Otherwise, price is per booking.', verbose_name='per person')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fa-motorcycle)', max_length=50, verbose_name='icon class')),
                ('image', models.ImageField(blank=True, upload_to='addons/', verbose_name='image')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'package addon',
                'verbose_name_plural': 'package addons',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fa-car)', max_length=50, verbose_name='icon class')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'package category',
                'verbose_name_plural': 'package categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fa-utensils)', max_length=50, verbose_name='icon class')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'package inclusion',
                'verbose_name_plural': 'package inclusions',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='short description')),
                ('transportation_type', models.CharField(choices=[('self_drive', 'Self Drive'), ('bus', 'Bus Transportation'), ('4x4', '4x4 Transportation')], max_length=20, verbose_name='transportation type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('child_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='child price')),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='duration (hours)')),
                ('pickup_time_start', models.TimeField(blank=True, null=True, verbose_name='pickup time start')),
                ('pickup_time_end', models.TimeField(blank=True, null=True, verbose_name='pickup time end')),
                ('dropoff_time_start', models.TimeField(blank=True, null=True, verbose_name='dropoff time start')),
                ('dropoff_time_end', models.TimeField(blank=True, null=True, verbose_name='dropoff time end')),
                ('featured_image', models.ImageField(blank=True, upload_to='packages/', verbose_name='featured image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='packages.packagecategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/gallery/', verbose_name='image')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='alt text')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='packages.package', verbose_name='package')),
            ],
            options={
                'verbose_name': 'package image',
                'verbose_name_plural': 'package images',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PackageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the reviewer if not a registered user', max_length=100, verbose_name='name')),
                ('email', models.EmailField(blank=True, help_text='Email of the reviewer if not a registered user', max_length=254, verbose_name='email')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], verbose_name='rating')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('comment', models.TextField(verbose_name='comment')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='packages.package', verbose_name='package')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_reviews', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'package review',
                'verbose_name_plural': 'package reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageAddonRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, help_text='Special price for this addon when purchased with this package. Leave blank to use the default addon price.', max_digits=10, null=True, verbose_name='special price')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_relations', to='packages.packageaddon', verbose_name='addon')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_relations', to='packages.package', verbose_name='package')),
            ],
            options={
                'verbose_name': 'package addon relation',
                'verbose_name_plural': 'package addon relations',
                'unique_together': {('package', 'addon')},
            },
        ),
        migrations.CreateModel(
            name='PackageInclusionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_relations', to='packages.packageinclusion', verbose_name='inclusion')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusion_relations', to='packages.package', verbose_name='package')),
            ],
            options={
                'verbose_name': 'package inclusion relation',
                'verbose_name_plural': 'package inclusion relations',
                'unique_together': {('package', 'inclusion')},
            },
        ),
    ]
