# Generated by Django 4.2.10 on 2025-05-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_customer_sms', models.BooleanField(default=True, help_text='Send SMS notifications to customers for booking confirmations', verbose_name='Enable customer SMS notifications')),
                ('enable_admin_sms', models.BooleanField(default=True, help_text='Send SMS notifications to admin for new bookings', verbose_name='Enable admin SMS notifications')),
                ('twilio_account_sid', models.CharField(blank=True, help_text='Your Twilio Account SID', max_length=255, verbose_name='Twilio Account SID')),
                ('twilio_auth_token', models.CharField(blank=True, help_text='Your Twilio Auth Token', max_length=255, verbose_name='Twilio Auth Token')),
                ('twilio_phone_number', models.CharField(blank=True, help_text='Your Twilio phone number in E.164 format (e.g., +15005550006)', max_length=20, verbose_name='Twilio Phone Number')),
                ('admin_phone_number', models.CharField(blank=True, help_text='Admin phone number to receive booking notifications in E.164 format (e.g., +971501234567)', max_length=20, verbose_name='Admin Phone Number')),
            ],
            options={
                'verbose_name': 'SMS Configuration',
                'verbose_name_plural': 'SMS Configuration',
            },
        ),
    ]
