# Generated by Django 5.2.1 on 2025-05-22 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emirate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'emirate',
                'verbose_name_plural': 'emirates',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('landmark', models.CharField(blank=True, max_length=200, verbose_name='landmark')),
                ('google_maps_link', models.URLField(blank=True, verbose_name='Google Maps link')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude')),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional cost for pickup from this location', max_digits=10, verbose_name='additional cost')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('emirate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_locations', to='locations.emirate', verbose_name='emirate')),
            ],
            options={
                'verbose_name': 'pickup location',
                'verbose_name_plural': 'pickup locations',
                'ordering': ['emirate', 'display_order', 'name'],
            },
        ),
    ]
