# Generated by Django 5.2.1 on 2025-05-22 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='booking ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('booking_date', models.DateField(verbose_name='booking date')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('nationality', models.CharField(blank=True, max_length=50, verbose_name='nationality')),
                ('adults', models.PositiveSmallIntegerField(default=1, verbose_name='number of adults')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='number of children')),
                ('pickup_location', models.CharField(blank=True, max_length=255, verbose_name='pickup location')),
                ('pickup_time', models.TimeField(blank=True, null=True, verbose_name='pickup time')),
                ('hotel_name', models.CharField(blank=True, max_length=100, verbose_name='hotel name')),
                ('hotel_room', models.CharField(blank=True, max_length=20, verbose_name='hotel room')),
                ('special_requests', models.TextField(blank=True, verbose_name='special requests')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash on Pickup')], default='credit_card', max_length=20, verbose_name='payment method')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total price')),
                ('payment_id', models.CharField(blank=True, max_length=100, verbose_name='payment ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='packages.package', verbose_name='package')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at the time of booking', max_digits=10, verbose_name='price')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.packageaddon', verbose_name='addon')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='bookings.booking', verbose_name='booking')),
            ],
            options={
                'verbose_name': 'booking addon',
                'verbose_name_plural': 'booking addons',
                'unique_together': {('booking', 'addon')},
            },
        ),
    ]
