# Generated by Django 5.2.1 on 2025-05-22 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_pickup_location'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='locations.pickuplocation', verbose_name='pickup location'),
        ),
    ]
