# Generated by Django 4.2.10 on 2025-05-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_pickup_location'),
    ]

    operations = [
    ]
